### ISSUE TITLE
Detail & tuneup

### ISSUE THREAD

**Issue by jglovier** [jglovier/project-car#5]
**TODO**

## Detail
- [x] Detail inside
- [x] Wash & wax

## Tune up

- [x] oil change (synthetic only), and replace with Purolator PUREOne (no FRAM!)
- [ ] ~~replace air filter (K&N)~~ (do later)
- [x] replace spark plugs with iridium plugs

**Comment by jglovier** [comment]
Replaced the plugs today with Dad.

![image](https://cloud.githubusercontent.com/assets/1319791/9418723/26afabc6-4824-11e5-9fd2-61b1b9cec0d0.png)
![image](https://cloud.githubusercontent.com/assets/1319791/9418728/2b7e17e6-4824-11e5-93fa-d7c930757868.png)
![image](https://cloud.githubusercontent.com/assets/1319791/9418733/2fbf12ec-4824-11e5-943a-dfcdaef51342.png)
